<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SysPrefsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('sys_prefs')->insert([
            [
                'name' => 'accounts_alpha',
                'category' => 'glsetup.general',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'accumulate_shipping',
                'category' => 'glsetup.customer',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'add_pct',
                'category' => 'setup.company',
                'type' => 'int',
                'length' => 5,
                'value' => '-1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'allow_negative_prices',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'allow_negative_stock',
                'category' => 'glsetup.inventory',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'alternative_tax_include_on_docs',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'auto_curr_reval',
                'category' => 'setup.company',
                'type' => 'smallint',
                'length' => 6,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'bank_charge_act',
                'category' => 'glsetup.general',
                'type' => 'varchar',
                'length' => 15,
                'value' => '5690',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'barcodes_on_stock',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'base_sales',
                'category' => 'setup.company',
                'type' => 'int',
                'length' => 11,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'bcc_email',
                'category' => 'setup.company',
                'type' => 'varchar',
                'length' => 100,
                'value' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'company_logo_on_views',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'company_logo_report',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'coy_logo',
                'category' => 'setup.company',
                'type' => 'varchar',
                'length' => 100,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'coy_name',
                'category' => 'setup.company',
                'type' => 'varchar',
                'length' => 60,
                'value' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'coy_no',
                'category' => 'setup.company',
                'type' => 'varchar',
                'length' => 25,
                'value' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'creditors_act',
                'category' => 'glsetup.purchase',
                'type' => 'varchar',
                'length' => 15,
                'value' => '2100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'curr_default',
                'category' => 'setup.company',
                'type' => 'char',
                'length' => 3,
                'value' => 'USD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'debtors_act',
                'category' => 'glsetup.sales',
                'type' => 'varchar',
                'length' => 15,
                'value' => '1200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_adj_act',
                'category' => 'glsetup.items',
                'type' => 'varchar',
                'length' => 15,
                'value' => '5040',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_cogs_act',
                'category' => 'glsetup.items',
                'type' => 'varchar',
                'length' => 15,
                'value' => '5010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_credit_limit',
                'category' => 'glsetup.customer',
                'type' => 'int',
                'length' => 11,
                'value' => '1000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_delivery_required',
                'category' => 'glsetup.sales',
                'type' => 'smallint',
                'length' => 6,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_dim_required',
                'category' => 'glsetup.dims',
                'type' => 'int',
                'length' => 11,
                'value' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_inv_sales_act',
                'category' => 'glsetup.items',
                'type' => 'varchar',
                'length' => 15,
                'value' => '4010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_inventory_act',
                'category' => 'glsetup.items',
                'type' => 'varchar',
                'length' => 15,
                'value' => '1510',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_loss_on_asset_disposal_act',
                'category' => 'glsetup.items',
                'type' => 'varchar',
                'length' => 15,
                'value' => '5660',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_prompt_payment_act',
                'category' => 'glsetup.sales',
                'type' => 'varchar',
                'length' => 15,
                'value' => '4500',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_quote_valid_days',
                'category' => 'glsetup.sales',
                'type' => 'smallint',
                'length' => 6,
                'value' => '30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_receival_required',
                'category' => 'glsetup.purchase',
                'type' => 'smallint',
                'length' => 6,
                'value' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_sales_act',
                'category' => 'glsetup.sales',
                'type' => 'varchar',
                'length' => 15,
                'value' => '4010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_sales_discount_act',
                'category' => 'glsetup.sales',
                'type' => 'varchar',
                'length' => 15,
                'value' => '4510',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_wip_act',
                'category' => 'glsetup.items',
                'type' => 'varchar',
                'length' => 15,
                'value' => '1530',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'default_workorder_required',
                'category' => 'glsetup.manuf',
                'type' => 'int',
                'length' => 11,
                'value' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'deferred_income_act',
                'category' => 'glsetup.sales',
                'type' => 'varchar',
                'length' => 15,
                'value' => '2105',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'depreciation_period',
                'category' => 'glsetup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'dim_on_recurrent_invoice',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'domicile',
                'category' => 'setup.company',
                'type' => 'varchar',
                'length' => 55,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'email',
                'category' => 'setup.company',
                'type' => 'varchar',
                'length' => 100,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'exchange_diff_act',
                'category' => 'glsetup.general',
                'type' => 'varchar',
                'length' => 15,
                'value' => '4450',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'f_year',
                'category' => 'setup.company',
                'type' => 'int',
                'length' => 11,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'fax',
                'category' => 'setup.company',
                'type' => 'varchar',
                'length' => 30,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'freight_act',
                'category' => 'glsetup.customer',
                'type' => 'varchar',
                'length' => 15,
                'value' => '4430',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'gl_closing_date',
                'category' => 'setup.closing_date',
                'type' => 'date',
                'length' => 8,
                'value' => '2000-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'grn_clearing_act',
                'category' => 'glsetup.purchase',
                'type' => 'varchar',
                'length' => 15,
                'value' => '1550',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'gst_no',
                'category' => 'setup.company',
                'type' => 'varchar',
                'length' => 25,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'legal_text',
                'category' => 'glsetup.customer',
                'type' => 'tinytext',
                'length' => 0,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'loc_notification',
                'category' => 'glsetup.inventory',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'login_tout',
                'category' => 'setup.company',
                'type' => 'smallint',
                'length' => 6,
                'value' => '600',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'long_description_invoice',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'max_days_in_docs',
                'category' => 'setup.company',
                'type' => 'smallint',
                'length' => 5,
                'value' => '180',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'no_customer_list',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'no_item_list',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'no_supplier_list',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'no_zero_lines_amount',
                'category' => 'glsetup.sales',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'past_due_days',
                'category' => 'glsetup.general',
                'type' => 'int',
                'length' => 11,
                'value' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'phone',
                'category' => 'setup.company',
                'type' => 'varchar',
                'length' => 30,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'po_over_charge',
                'category' => 'glsetup.purchase',
                'type' => 'int',
                'length' => 11,
                'value' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'po_over_receive',
                'category' => 'glsetup.purchase',
                'type' => 'int',
                'length' => 11,
                'value' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'postal_address',
                'category' => 'setup.company',
                'type' => 'tinytext',
                'length' => 0,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'print_dialog_direct',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'print_invoice_no',
                'category' => 'glsetup.sales',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'print_item_images_on_quote',
                'category' => 'glsetup.inventory',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'profit_loss_year_act',
                'category' => 'glsetup.general',
                'type' => 'varchar',
                'length' => 15,
                'value' => '9990',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'pyt_discount_act',
                'category' => 'glsetup.purchase',
                'type' => 'varchar',
                'length' => 15,
                'value' => '5060',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ref_no_auto_increase',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'retained_earnings_act',
                'category' => 'glsetup.general',
                'type' => 'varchar',
                'length' => 15,
                'value' => '3590',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'round_to',
                'category' => 'setup.company',
                'type' => 'int',
                'length' => 5,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'shortname_name_in_list',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'show_po_item_codes',
                'category' => 'glsetup.purchase',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'suppress_tax_rates',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'tax_algorithm',
                'category' => 'glsetup.customer',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'tax_last',
                'category' => 'setup.company',
                'type' => 'int',
                'length' => 11,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'tax_prd',
                'category' => 'setup.company',
                'type' => 'int',
                'length' => 11,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'time_zone',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'use_dimension',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'use_fixed_assets',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'use_manufacturing',
                'category' => 'setup.company',
                'type' => 'tinyint',
                'length' => 1,
                'value' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'version_id',
                'category' => 'system',
                'type' => 'varchar',
                'length' => 11,
                'value' => '2.4.1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
